compressionLevel: mixed

enableGlobalCache: false

enableInlineBuilds: true

enableMirror: false

enableTelemetry: false

enableTips: false

nodeLinker: node-modules

npmRegistryServer: 'https://artifactorybase.service.csnzoo.com/artifactory/api/npm/npm'

supportedArchitectures:
  {
    os: ['current', 'darwin', 'linux', 'win32'],
    cpu: ['current', 'x64', 'ia32', 'arm64'],
    libc: ['current', 'glibc', 'musl'],
  }
