name: api.mock
channels:
  - apple
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - ipydatagrid
  - jupyterlab==4.0.11
  - nb_conda_kernels==2.3.1
  - notebook==7.0.7
  - openpyxl
  - pip
  - poetry==1.8.3
  - filelock==3.15.4 # dependency for poetry
  - python==3.10.13

variables:
  GRPC_PYTHON_BUILD_SYSTEM_OPENSSL: 1
  GRPC_PYTHON_BUILD_SYSTEM_ZLIB: 1
