/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from "@tanstack/react-router"

// Import Routes

import { Route as rootRoute } from "./routes/__root"
import { Route as PublicImport } from "./routes/_public"
import { Route as AuthenticatedImport } from "./routes/_authenticated"
import { Route as AuthenticatedIndexImport } from "./routes/_authenticated/index"
import { Route as AuthenticatedServicemapImport } from "./routes/_authenticated/servicemap"
import { Route as PublicMLoginImport } from "./routes/_public/m.login"

// Create Virtual Routes

const AuthenticatedDashboardLazyImport = createFileRoute(
  "/_authenticated/dashboard",
)()
const AuthenticatedMenuLevelMenuLevel1aLazyImport = createFileRoute(
  "/_authenticated/menu-level/menu-level-1a",
)()
const AuthenticatedMAboutLazyImport = createFileRoute(
  "/_authenticated/m/about",
)()
const AuthenticatedMenuLevelMenuLevel1bMenuLevel2bLazyImport = createFileRoute(
  "/_authenticated/menu-level/menu-level-1b/menu-level-2b",
)()
const AuthenticatedMenuLevelMenuLevel1bMenuLevel2aLazyImport = createFileRoute(
  "/_authenticated/menu-level/menu-level-1b/menu-level-2a",
)()

// Create/Update Routes

const PublicRoute = PublicImport.update({
  id: "/_public",
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import("./routes/_authenticated.lazy").then((d) => d.Route),
)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  path: "/",
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedDashboardLazyRoute = AuthenticatedDashboardLazyImport.update(
  {
    path: "/dashboard",
    getParentRoute: () => AuthenticatedRoute,
  } as any,
).lazy(() =>
  import("./routes/_authenticated/dashboard.lazy").then((d) => d.Route),
)

const AuthenticatedServicemapRoute = AuthenticatedServicemapImport.update({
  path: "/servicemap",
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import("./routes/_authenticated/servicemap.lazy").then((d) => d.Route),
)

const AuthenticatedMenuLevelMenuLevel1aLazyRoute =
  AuthenticatedMenuLevelMenuLevel1aLazyImport.update({
    path: "/menu-level/menu-level-1a",
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import("./routes/_authenticated/menu-level.menu-level-1a.lazy").then(
      (d) => d.Route,
    ),
  )

const AuthenticatedMAboutLazyRoute = AuthenticatedMAboutLazyImport.update({
  path: "/m/about",
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import("./routes/_authenticated/m.about.lazy").then((d) => d.Route),
)

const PublicMLoginRoute = PublicMLoginImport.update({
  path: "/m/login",
  getParentRoute: () => PublicRoute,
} as any).lazy(() =>
  import("./routes/_public/m.login.lazy").then((d) => d.Route),
)

const AuthenticatedMenuLevelMenuLevel1bMenuLevel2bLazyRoute =
  AuthenticatedMenuLevelMenuLevel1bMenuLevel2bLazyImport.update({
    path: "/menu-level/menu-level-1b/menu-level-2b",
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import(
      "./routes/_authenticated/menu-level.menu-level-1b.menu-level-2b.lazy"
    ).then((d) => d.Route),
  )

const AuthenticatedMenuLevelMenuLevel1bMenuLevel2aLazyRoute =
  AuthenticatedMenuLevelMenuLevel1bMenuLevel2aLazyImport.update({
    path: "/menu-level/menu-level-1b/menu-level-2a",
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import(
      "./routes/_authenticated/menu-level.menu-level-1b.menu-level-2a.lazy"
    ).then((d) => d.Route),
  )

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_authenticated": {
      id: "/_authenticated"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    "/_public": {
      id: "/_public"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof PublicImport
      parentRoute: typeof rootRoute
    }
    "/_authenticated/servicemap": {
      id: "/_authenticated/servicemap"
      path: "/servicemap"
      fullPath: "/servicemap"
      preLoaderRoute: typeof AuthenticatedServicemapImport
      parentRoute: typeof AuthenticatedImport
    }
    "/_authenticated/dashboard": {
      id: "/_authenticated/dashboard"
      path: "/dashboard"
      fullPath: "/dashboard"
      preLoaderRoute: typeof AuthenticatedDashboardLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    "/_authenticated/": {
      id: "/_authenticated/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    "/_public/m/login": {
      id: "/_public/m/login"
      path: "/m/login"
      fullPath: "/m/login"
      preLoaderRoute: typeof PublicMLoginImport
      parentRoute: typeof PublicImport
    }
    "/_authenticated/m/about": {
      id: "/_authenticated/m/about"
      path: "/m/about"
      fullPath: "/m/about"
      preLoaderRoute: typeof AuthenticatedMAboutLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    "/_authenticated/menu-level/menu-level-1a": {
      id: "/_authenticated/menu-level/menu-level-1a"
      path: "/menu-level/menu-level-1a"
      fullPath: "/menu-level/menu-level-1a"
      preLoaderRoute: typeof AuthenticatedMenuLevelMenuLevel1aLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    "/_authenticated/menu-level/menu-level-1b/menu-level-2a": {
      id: "/_authenticated/menu-level/menu-level-1b/menu-level-2a"
      path: "/menu-level/menu-level-1b/menu-level-2a"
      fullPath: "/menu-level/menu-level-1b/menu-level-2a"
      preLoaderRoute: typeof AuthenticatedMenuLevelMenuLevel1bMenuLevel2aLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    "/_authenticated/menu-level/menu-level-1b/menu-level-2b": {
      id: "/_authenticated/menu-level/menu-level-1b/menu-level-2b"
      path: "/menu-level/menu-level-1b/menu-level-2b"
      fullPath: "/menu-level/menu-level-1b/menu-level-2b"
      preLoaderRoute: typeof AuthenticatedMenuLevelMenuLevel1bMenuLevel2bLazyImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  AuthenticatedRoute: AuthenticatedRoute.addChildren({
    AuthenticatedServicemapRoute,
    AuthenticatedDashboardLazyRoute,
    AuthenticatedIndexRoute,
    AuthenticatedMAboutLazyRoute,
    AuthenticatedMenuLevelMenuLevel1aLazyRoute,
    AuthenticatedMenuLevelMenuLevel1bMenuLevel2aLazyRoute,
    AuthenticatedMenuLevelMenuLevel1bMenuLevel2bLazyRoute,
  }),
  PublicRoute: PublicRoute.addChildren({ PublicMLoginRoute }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/_public"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/servicemap",
        "/_authenticated/dashboard",
        "/_authenticated/",
        "/_authenticated/m/about",
        "/_authenticated/menu-level/menu-level-1a",
        "/_authenticated/menu-level/menu-level-1b/menu-level-2a",
        "/_authenticated/menu-level/menu-level-1b/menu-level-2b"
      ]
    },
    "/_public": {
      "filePath": "_public.tsx",
      "children": [
        "/_public/m/login"
      ]
    },
    "/_authenticated/servicemap": {
      "filePath": "_authenticated/servicemap.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboard": {
      "filePath": "_authenticated/dashboard.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    },
    "/_public/m/login": {
      "filePath": "_public/m.login.tsx",
      "parent": "/_public"
    },
    "/_authenticated/m/about": {
      "filePath": "_authenticated/m.about.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/menu-level/menu-level-1a": {
      "filePath": "_authenticated/menu-level.menu-level-1a.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/menu-level/menu-level-1b/menu-level-2a": {
      "filePath": "_authenticated/menu-level.menu-level-1b.menu-level-2a.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/menu-level/menu-level-1b/menu-level-2b": {
      "filePath": "_authenticated/menu-level.menu-level-1b.menu-level-2b.lazy.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
