/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from "@tanstack/react-router"

// Import Routes

import { Route as rootRoute } from "./routes/__root"
import { Route as PublicImport } from "./routes/_public"
import { Route as AuthenticatedImport } from "./routes/_authenticated"
import { Route as AuthenticatedIndexImport } from "./routes/_authenticated/index"
import { Route as PublicLoginImport } from "./routes/_public/login"
import { Route as AuthenticatedServicemapImport } from "./routes/_authenticated/servicemap"
import { Route as AuthenticatedIndexSplatImport } from "./routes/_authenticated/index.$"

// Create Virtual Routes

const AuthenticatedMonitorLazyImport = createFileRoute(
  "/_authenticated/monitor",
)()
const AuthenticatedDashboardLazyImport = createFileRoute(
  "/_authenticated/dashboard",
)()
const AuthenticatedAboutLazyImport = createFileRoute("/_authenticated/about")()

// Create/Update Routes

const PublicRoute = PublicImport.update({
  id: "/_public",
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import("./routes/_authenticated.lazy").then((d) => d.Route),
)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  path: "/",
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedMonitorLazyRoute = AuthenticatedMonitorLazyImport.update({
  path: "/monitor",
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import("./routes/_authenticated/monitor.lazy").then((d) => d.Route),
)

const AuthenticatedDashboardLazyRoute = AuthenticatedDashboardLazyImport.update(
  {
    path: "/dashboard",
    getParentRoute: () => AuthenticatedRoute,
  } as any,
).lazy(() =>
  import("./routes/_authenticated/dashboard.lazy").then((d) => d.Route),
)

const AuthenticatedAboutLazyRoute = AuthenticatedAboutLazyImport.update({
  path: "/about",
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import("./routes/_authenticated/about.lazy").then((d) => d.Route),
)

const PublicLoginRoute = PublicLoginImport.update({
  path: "/login",
  getParentRoute: () => PublicRoute,
} as any).lazy(() => import("./routes/_public/login.lazy").then((d) => d.Route))

const AuthenticatedServicemapRoute = AuthenticatedServicemapImport.update({
  path: "/servicemap",
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import("./routes/_authenticated/servicemap.lazy").then((d) => d.Route),
)

const AuthenticatedIndexSplatRoute = AuthenticatedIndexSplatImport.update({
  path: "/index/$",
  getParentRoute: () => AuthenticatedRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_authenticated": {
      id: "/_authenticated"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    "/_public": {
      id: "/_public"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof PublicImport
      parentRoute: typeof rootRoute
    }
    "/_authenticated/servicemap": {
      id: "/_authenticated/servicemap"
      path: "/servicemap"
      fullPath: "/servicemap"
      preLoaderRoute: typeof AuthenticatedServicemapImport
      parentRoute: typeof AuthenticatedImport
    }
    "/_public/login": {
      id: "/_public/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof PublicLoginImport
      parentRoute: typeof PublicImport
    }
    "/_authenticated/about": {
      id: "/_authenticated/about"
      path: "/about"
      fullPath: "/about"
      preLoaderRoute: typeof AuthenticatedAboutLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    "/_authenticated/dashboard": {
      id: "/_authenticated/dashboard"
      path: "/dashboard"
      fullPath: "/dashboard"
      preLoaderRoute: typeof AuthenticatedDashboardLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    "/_authenticated/monitor": {
      id: "/_authenticated/monitor"
      path: "/monitor"
      fullPath: "/monitor"
      preLoaderRoute: typeof AuthenticatedMonitorLazyImport
      parentRoute: typeof AuthenticatedImport
    }
    "/_authenticated/": {
      id: "/_authenticated/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    "/_authenticated/index/$": {
      id: "/_authenticated/index/$"
      path: "/index/$"
      fullPath: "/index/$"
      preLoaderRoute: typeof AuthenticatedIndexSplatImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  AuthenticatedRoute: AuthenticatedRoute.addChildren({
    AuthenticatedServicemapRoute,
    AuthenticatedAboutLazyRoute,
    AuthenticatedDashboardLazyRoute,
    AuthenticatedMonitorLazyRoute,
    AuthenticatedIndexRoute,
    AuthenticatedIndexSplatRoute,
  }),
  PublicRoute: PublicRoute.addChildren({ PublicLoginRoute }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/_public"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/servicemap",
        "/_authenticated/about",
        "/_authenticated/dashboard",
        "/_authenticated/monitor",
        "/_authenticated/",
        "/_authenticated/index/$"
      ]
    },
    "/_public": {
      "filePath": "_public.tsx",
      "children": [
        "/_public/login"
      ]
    },
    "/_authenticated/servicemap": {
      "filePath": "_authenticated/servicemap.tsx",
      "parent": "/_authenticated"
    },
    "/_public/login": {
      "filePath": "_public/login.tsx",
      "parent": "/_public"
    },
    "/_authenticated/about": {
      "filePath": "_authenticated/about.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboard": {
      "filePath": "_authenticated/dashboard.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/monitor": {
      "filePath": "_authenticated/monitor.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/index/$": {
      "filePath": "_authenticated/index.$.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
